server {
    listen 443 ssl;
    server_name cmakario.42.de;

    # ssl_certificate     /etc/ssl/certs/cert.pem;
    # ssl_certificate_key /etc/ssl/private/key.pem;
    ssl_certificate     /etc/ssl/certs/cmakario.42.de.crt;
    ssl_certificate_key /etc/ssl/private/cmakario.42.de.key;


    root /var/www/html;
    index index.php index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass wordpress:9000;
    }
}
