services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    restart: unless-stopped

    environment:
      WP_DB_NAME: ${WP_DB_NAME}
      WP_DB_USER: ${WP_DB_USER}
      MYSQL_DATABASE: ${WP_DB_NAME}
      MYSQL_USER:     ${WP_DB_USER}
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password

    secrets:
      - db_password
      - db_root_password

    volumes:
      - mariadb_data:/var/lib/mysql

    networks:
      - inception_net

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      interval: 30s
      start_period: 60s

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    restart: unless-stopped

    depends_on:
      mariadb:
        condition: service_healthy

    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_NAME: ${WP_DB_NAME}
      WORDPRESS_DB_USER: ${WP_DB_USER}
      WP_URL: https://cmakario.42.de
      WP_TITLE: YourTitle
      WP_ADMIN_USER: admin
      WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
      WP_ADMIN_EMAIL: you@example.com
      WP_USER_NAME: author
      WP_USER_EMAIL: author@example.com
      WP_USER_PASSWORD: ${WP_USER_PASSWORD}
      WP_USER_ROLE: author

    secrets:
      - db_password
      - wp_admin_password
      - wp_user_password

    volumes:
      - wordpress_data:/var/www/html

    networks:
      - inception_net

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    restart: unless-stopped

    depends_on:
      - wordpress

    ports:
      - "443:443"
      - "80:80"

    volumes:
      - wordpress_data:/var/www/html

    networks:
      - inception_net

secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  wp_user_password:
    file: ../secrets/wp_user_password.txt

networks:
  inception_net:
    driver: bridge

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/cmakario/data/wordpress
      o: bind

  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/cmakario/data/mariadb
      o: bind
